config/routes.rb
Rails.application.routes.draw do
  devise_for :moussailons
    
  root 'home#index'

  get 'home/private'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moussailon.rb
class Moussailon < ApplicationRecord
    has_many :gossip
    
    
    attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    validates :username, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A[a-zA-Z0-9]+\Z/ }
    
    
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable
    
    def self.find_first_by_auth_conditions(warden_conditions)
    
        conditions = warden_conditions.dup
        if login = conditions.delete(:login)
            where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
        else
            where(conditions.to_hash).first
        end
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    
    attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    validates :username, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A[a-zA-Z0-9]+\Z/ }
    
    
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable
    
    def self.find_first_by_auth_conditions(warden_conditions)
    
        conditions = warden_conditions.dup
        if login = conditions.delete(:login)
            where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
        else
            where(conditions.to_hash).first
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
    before_action :configure_devise_parameters, if: :devise_controller?
    
    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def private
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Bienvenue sur mon site</h1>
<p>
    
   <% if moussailon_signed_in? %>
    <%= link_to 'Se déconnecter', destroy_moussailon_session_path, method: :delete %>
    <% else %>
    <%= link_to 'se connecter', new_moussailon_session_path %>
    <% end %>
    </p>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
  <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
     
    <%= yield %>
  </body>
</html>